server {
  listen 8080;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location /debug {
    try_files $uri $uri/ /debug.html;
  }

  location /admin {
    try_files $uri $uri/ /admin/index.html;
  }
  
  location / {
    try_files $uri $uri/ /index.html;
  }

  # (voliteľné) základné cache pre statické assets
  location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
    expires 1h;
    add_header Cache-Control "public";
  }
}
