services:
  rp-frontend:
    image: nginx:latest
    container_name: rp-frontend
    volumes:
      - ../frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../frontend/src:/usr/share/nginx/html
    networks:
      ssnd-network:
        ipv4_address: 172.18.1.4

networks:
  ssnd-network:
    name: ssnd
    external: true
